# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint-analyze-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: docker-compose run --rm composer install

      - name: Linting
        run: docker-compose run --rm composer run lint

      - name: Analyzing
        run: docker-compose run --rm composer run analyze

      - name: Testing
        run: docker-compose run --rm composer run test

  coverage:
    needs: [ lint-analyze-test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker-compose run --rm composer install
      - uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ce2820c8535ccf766ce5a4b2c55bc99d2072602373c8a38d19a981eb14000854
        with:
          coverageCommand: docker-compose run --rm test-coverage
          coverageLocations: ${{github.workspace}}/build/logs/clover.xml:clover


